:guid: %guid%
:ssh_command: %ssh_command%
:ssh_password: %ssh_password%
:ssh_username: %ssh_username%
:targethost_fqdn: %targethost%
:markup-in-source: verbatim,attributes,quotes
:show_solution: true
:format_cmd_exec: source,options="nowrap",subs="{markup-in-source}",role="copy"
:format_cmd_exec2: source,options="nowrap",subs="{markup-in-source}",role="copy"
:format_cmd_output: bash,options="nowrap",subs="{markup-in-source}"
ifeval::["%cloud_provider%" == "ec2"]
:format_cmd_exec: source,options="nowrap",subs="{markup-in-source}",role="execute"
:format_cmd_exec2: source,options="nowrap",subs="{markup-in-source}",role="execute-2"
endif::[]




WARNING:  Executing these setup tasks is a requirement before proceeding with the workshop exercises.

== Workshop Setup

These steps should be easy to click-through if you are using the bookbag terminal. 

Connect to target host (bastion) via ssh:

[{format_cmd_exec}]
----
*{ssh_command} -o "StrictHostKeyChecking no"*
----

Send the password:

[{format_cmd_exec}]
----
*{ssh_password}*
----

Launch a 'tmux' (terminal multiplexer):

[{format_cmd_exec}]
----
*tmux*
----

Use sudo to escalate your user priviledges:

[{format_cmd_exec}]
----
*sudo -i*
----

And finally, execute the workshop setup script:

[{format_cmd_exec}]
----
*cd ~/RHEL9-Workshop; ./rhel9-workshop.sh all*
----

The setup will take about 8 minutes.  We will use this time to review RHEL 8 at a highlevel, talk about the workshop and help you get the most value out of your experience today.


== Set Up Terminal 2

Like wise, let us proceed to set up the second terminal for use later.

[{format_cmd_exec2}]
----
*{ssh_command} -o "StrictHostKeyChecking no"*
----

[{format_cmd_exec2}]
----
*{ssh_password}*
----

[{format_cmd_exec2}]
----
*tmux*
----

[{format_cmd_exec2}]
----
*sudo -i*
----

== Connection Information

[bash,options="nowrap",subs="{markup-in-source}"]

  * Unique session GUID: *{guid}*

  * Target host FQDN: *{targethost_fqdn}*

  * Username: *{ssh_username}*

  * Password: *{ssh_password}*

For easy access, here is the ssh command (and password) you can copy to your paste buffer.

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
*{ssh_command} -o "StrictHostKeyChecking no"*
----

[source,options="nowrap",subs="{markup-in-source}",role="copy"]
----
*{ssh_password}*
----

